
services:
  httpenv:
    image: "${TESTING_IMAGE}"
    command: /httpenv
    ports:
      - 8888:8888

  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      httpenv:
        condition: service_started
    # run all your tests here against the allhands22 service
    command: curl --fail http://httpenv:8888 || exit 1